package com.tstudioz.fax.fme.testStuff

import com.tstudioz.fax.fme.feature.studomat.models.StudomatSubject
import com.tstudioz.fax.fme.feature.studomat.models.StudomatYearInfo


val studomatSubjectTestDataReal = listOf(
    StudomatSubject(
        "2023./2024.Korisnička sučelja1",
        "Korisnička sučelja",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "1",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "5",
        "4.9.2024.",
        "2023./2024.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2023./2024.Modeli računarstva1",
        "Modeli računarstva",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "1",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "2",
        "12.7.2024.",
        "2023./2024.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2023./2024.Numerička analiza1",
        "Numerička analiza",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "1",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "2",
        "8.2.2024.",
        "2023./2024.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2023./2024.Računalna grafika1",
        "Računalna grafika",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "1",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "3",
        "2.2.2024.",
        "2023./2024.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2023./2024.Umjetna inteligencija1",
        "Umjetna inteligencija",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "1",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "2",
        "6.2.2024.",
        "2023./2024.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2023./2024.Uvod u podatkovnu znanost1",
        "Uvod u podatkovnu znanost",
        "Izborni predmeti 1. sem.",
        "1",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "5",
        "5.2.2024.",
        "2023./2024.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2023./2024.IP komunikacije2",
        "IP komunikacije",
        "Izborni predmeti 2. sem",
        "2",
        "30",
        "30",
        "6,0",
        "Da",
        "obavljen (položen)",
        "3",
        "1.7.2024.",
        "2023./2024.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2023./2024.Jezici i prevoditelji2",
        "Jezici i prevoditelji",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "2",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "2",
        "28.6.2024.",
        "2023./2024.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2023./2024.Kriptografija i mrežna sigurnost2",
        "Kriptografija i mrežna sigurnost",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "2",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "5",
        "25.6.2024.",
        "2023./2024.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2023./2024.Metode optimizacije2",
        "Metode optimizacije",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "2",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "3",
        "4.7.2024.",
        "2023./2024.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2023./2024.Napredne računalne arhitekture2",
        "Napredne računalne arhitekture",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "2",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "4",
        "2.7.2024.",
        "2023./2024.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2023./2024.Podržano strojno učenje2",
        "Podržano strojno učenje",
        "Izborni predmeti 2. sem",
        "2",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "5",
        "27.6.2024.",
        "2023./2024.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2021./2022.Električna mjerenja3",
        "Električna mjerenja",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "3",
        "45",
        "30",
        "6,0",
        "Da",
        "obavljen (položen)",
        "2",
        "25.2.2022.",
        "2021./2022.",
        "Elektronika i računalno inženjerstvo",
        true
    ),
    StudomatSubject(
        "2021./2022.Elektrotehnički materijali i tehnologije4",
        "Elektrotehnički materijali i tehnologije",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "4",
        "30",
        "15",
        "4,0",
        "Da",
        "odslušan predmet",
        "podatak nije evidentiran",
        "podatak nije evidentiran",
        "2021./2022.",
        "Elektronika i računalno inženjerstvo",
        false
    ),
    StudomatSubject(
        "2021./2022.Analiza mreža5",
        "Analiza mreža",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "5",
        "30",
        "30",
        "5,0",
        "Da",
        "odslušan predmet",
        "podatak nije evidentiran",
        "podatak nije evidentiran",
        "2021./2022.",
        "Elektronika i računalno inženjerstvo",
        false
    ),
    StudomatSubject(
        "2021./2022.Arhitektura računala5",
        "Arhitektura računala",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "5",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "2",
        "10.2.2022.",
        "2021./2022.",
        "Elektronika i računalno inženjerstvo",
        true
    ),
    StudomatSubject(
        "2021./2022.Elektronički sklopovi5",
        "Elektronički sklopovi",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "5",
        "30",
        "30",
        "5,0",
        "Da",
        "odslušan predmet",
        "podatak nije evidentiran",
        "podatak nije evidentiran",
        "2021./2022.",
        "Elektronika i računalno inženjerstvo",
        false
    ),
    StudomatSubject(
        "2021./2022.Objektno orijentirano programiranje5",
        "Objektno orijentirano programiranje",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "5",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "4",
        "23.2.2022.",
        "2021./2022.",
        "Elektronika i računalno inženjerstvo",
        true
    ),
    StudomatSubject(
        "2021./2022.Programiranje za internet5",
        "Programiranje za internet",
        "Izborni predmeti 5. sem",
        "5",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "4",
        "23.2.2022.",
        "2021./2022.",
        "Elektronika i računalno inženjerstvo",
        true
    ),
    StudomatSubject(
        "2021./2022.Računalne mreže5",
        "Računalne mreže",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "5",
        "45",
        "15",
        "5,0",
        "Da",
        "obavljen (položen)",
        "3",
        "5.9.2022.",
        "2021./2022.",
        "Elektronika i računalno inženjerstvo",
        true
    ),
    StudomatSubject(
        "2021./2022.Baze podataka6",
        "Baze podataka",
        "Izborni predmeti 6. sem",
        "6",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "3",
        "30.6.2022.",
        "2021./2022.",
        "Elektronika i računalno inženjerstvo",
        true
    ),
    StudomatSubject(
        "2021./2022.Digitalna instrumentacija 16",
        "Digitalna instrumentacija 1",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "6",
        "30",
        "15",
        "5,0",
        "Da",
        "priznat ispit iz predmeta",
        "4",
        "7.10.2022.",
        "2021./2022.",
        "Elektronika i računalno inženjerstvo",
        true
    ),
    StudomatSubject(
        "2021./2022.Impulsni i digitalni sklopovi6",
        "Impulsni i digitalni sklopovi",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "6",
        "30",
        "30",
        "4,0",
        "Da",
        "obavljen (položen)",
        "2",
        "30.8.2022.",
        "2021./2022.",
        "Elektronika i računalno inženjerstvo",
        true
    ),
    StudomatSubject(
        "2021./2022.Operacijski sustavi6",
        "Operacijski sustavi",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "6",
        "45",
        "15",
        "5,0",
        "Da",
        "obavljen (položen)",
        "2",
        "27.6.2022.",
        "2021./2022.",
        "Elektronika i računalno inženjerstvo",
        true
    ),
    StudomatSubject(
        "2021./2022.Završni rad6",
        "Završni rad",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "6",
        "0",
        "15",
        "12,0",
        "Da",
        "ima nasljednika - zbog nepolaganja ispita",
        "podatak nije evidentiran",
        "podatak nije evidentiran",
        "2021./2022.",
        "Elektronika i računalno inženjerstvo",
        false
    ),
    StudomatSubject(
        "2022./2023.Elektrotehnika1",
        "Elektrotehnika",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "1",
        "45",
        "30",
        "7,0",
        "Da",
        "priznat ispit iz predmeta",
        "4",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Engleski jezik 11",
        "Engleski jezik 1",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "1",
        "30",
        "0",
        "2,0",
        "Da",
        "priznat ispit iz predmeta",
        "4",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Fizika 11",
        "Fizika 1",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "1",
        "45",
        "30",
        "7,0",
        "Da",
        "priznat ispit iz predmeta",
        "3",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Matematika 11",
        "Matematika 1",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "1",
        "45",
        "45",
        "7,0",
        "Da",
        "priznat ispit iz predmeta",
        "4",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Uvod u računala i programiranje1",
        "Uvod u računala i programiranje",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "1",
        "45",
        "30",
        "7,0",
        "Da",
        "priznat ispit iz predmeta",
        "4",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Elektronika2",
        "Elektronika",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "2",
        "45",
        "30",
        "7,0",
        "Da",
        "priznat ispit iz predmeta",
        "2",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Engleski jezik 22",
        "Engleski jezik 2",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "2",
        "30",
        "0",
        "2,0",
        "Da",
        "priznat ispit iz predmeta",
        "3",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Fizika 22",
        "Fizika 2",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "2",
        "45",
        "30",
        "7,0",
        "Da",
        "priznat ispit iz predmeta",
        "5",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Matematika 22",
        "Matematika 2",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "2",
        "45",
        "45",
        "7,0",
        "Da",
        "priznat ispit iz predmeta",
        "3",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Programiranje2",
        "Programiranje",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "2",
        "45",
        "30",
        "7,0",
        "Da",
        "priznat ispit iz predmeta",
        "4",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Diskretna matematika3",
        "Diskretna matematika",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "3",
        "30",
        "30",
        "6,0",
        "Da",
        "obavljen (položen)",
        "2",
        "31.1.2023.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Diskretni sustavi i strukture3",
        "Diskretni sustavi i strukture",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "3",
        "45",
        "45",
        "7,0",
        "Da",
        "priznat ispit iz predmeta",
        "3",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Komunikacijske vještine3",
        "Komunikacijske vještine",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "3",
        "30",
        "0",
        "2,0",
        "Da",
        "priznat ispit iz predmeta",
        "4",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Objektno orijentirano programiranje3",
        "Objektno orijentirano programiranje",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "3",
        "45",
        "30",
        "7,0",
        "Da",
        "priznat ispit iz predmeta",
        "4",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Praktikum3",
        "Praktikum",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "3",
        "0",
        "45",
        "2,0",
        "Da",
        "obavljen (položen)",
        "4",
        "24.2.2023.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Strukture podataka3",
        "Strukture podataka",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "3",
        "30",
        "30",
        "6,0",
        "Da",
        "obavljen (položen)",
        "4",
        "6.2.2023.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Algoritmi4",
        "Algoritmi",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "4",
        "45",
        "30",
        "7,0",
        "Da",
        "obavljen (položen)",
        "2",
        "12.6.2023.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Arhitektura digitalnih računala4",
        "Arhitektura digitalnih računala",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "4",
        "45",
        "30",
        "7,0",
        "Da",
        "priznat ispit iz predmeta",
        "2",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Baze podataka4",
        "Baze podataka",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "4",
        "30",
        "30",
        "6,0",
        "Da",
        "priznat ispit iz predmeta",
        "3",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Signali i sustavi4",
        "Signali i sustavi",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "4",
        "30",
        "30",
        "5,0",
        "Da",
        "priznat ispit iz predmeta",
        "2",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Vjerojatnost i statistika4",
        "Vjerojatnost i statistika",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "4",
        "30",
        "30",
        "5,0",
        "Da",
        "priznat ispit iz predmeta",
        "4",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Operacijski sustavi5",
        "Operacijski sustavi",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "5",
        "45",
        "30",
        "7,0",
        "Da",
        "priznat ispit iz predmeta",
        "2",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Programiranje za Unix5",
        "Programiranje za Unix",
        "Izborni predmeti 5. sem",
        "5",
        "30",
        "15",
        "4,0",
        "Da",
        "obavljen (položen)",
        "5",
        "3.2.2023.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Programiranje za internet5",
        "Programiranje za internet",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "5",
        "45",
        "30",
        "6,0",
        "Da",
        "priznat ispit iz predmeta",
        "4",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Programsko inženjerstvo5",
        "Programsko inženjerstvo",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "5",
        "45",
        "30",
        "7,0",
        "Da",
        "obavljen (položen)",
        "4",
        "2.2.2023.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Računalne mreže5",
        "Računalne mreže",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "5",
        "45",
        "30",
        "6,0",
        "Da",
        "priznat ispit iz predmeta",
        "3",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Digitalna instrumentacija 16",
        "Digitalna instrumentacija 1",
        "Izborni predmeti 6. sem",
        "6",
        "30",
        "15",
        "5,0",
        "Da",
        "priznat ispit iz predmeta",
        "4",
        "7.10.2022.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Poslovna informatika6",
        "Poslovna informatika",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "6",
        "30",
        "15",
        "4,0",
        "Da",
        "obavljen (položen)",
        "3",
        "15.6.2023.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Projektiranje informacijskih sustava6",
        "Projektiranje informacijskih sustava",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "6",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "3",
        "19.6.2023.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Uvod u distribuirane informacijske sustave6",
        "Uvod u distribuirane informacijske sustave",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "6",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "3",
        "13.6.2023.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2022./2023.Završni rad6",
        "Završni rad",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "6",
        "0",
        "15",
        "12,0",
        "Da",
        "obavljen (položen)",
        "5",
        "1.9.2023.",
        "2022./2023.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2020./2021.Ekonomika i organizacija proizvodnje3",
        "Ekonomika i organizacija proizvodnje",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "3",
        "30",
        "0",
        "3,0",
        "Da",
        "obavljen (položen)",
        "4",
        "8.2.2021.",
        "2020./2021.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2020./2021.Električna mjerenja3",
        "Električna mjerenja",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "3",
        "45",
        "30",
        "6,0",
        "Da",
        "ima nasljednika - zbog nepolaganja ispita",
        "podatak nije evidentiran",
        "podatak nije evidentiran",
        "2020./2021.",
        "Elektrotehnika i informacijska tehnologija",
        false
    ),
    StudomatSubject(
        "2020./2021.Elektronički elementi i sklopovi3",
        "Elektronički elementi i sklopovi",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "3",
        "30",
        "45",
        "6,0",
        "Da",
        "obavljen (položen)",
        "2",
        "16.2.2021.",
        "2020./2021.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2020./2021.Engleski jezik 33",
        "Engleski jezik 3",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "3",
        "30",
        "0",
        "3,0",
        "Da",
        "obavljen (položen)",
        "3",
        "17.2.2021.",
        "2020./2021.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2020./2021.Fizika 23",
        "Fizika 2",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "3",
        "45",
        "45",
        "7,0",
        "Da",
        "obavljen (položen)",
        "5",
        "4.3.2021.",
        "2020./2021.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2020./2021.Matematika 33",
        "Matematika 3",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "3",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "3",
        "10.2.2021.",
        "2020./2021.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2020./2021.Digitalna elektronika4",
        "Digitalna elektronika",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "4",
        "45",
        "30",
        "6,0",
        "Da",
        "obavljen (položen)",
        "3",
        "20.7.2021.",
        "2020./2021.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2020./2021.Elektrotehnički materijali i tehnologije4",
        "Elektrotehnički materijali i tehnologije",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "4",
        "30",
        "15",
        "4,0",
        "Da",
        "ima nasljednika - zbog nepolaganja ispita",
        "podatak nije evidentiran",
        "podatak nije evidentiran",
        "2020./2021.",
        "Elektrotehnika i informacijska tehnologija",
        false
    ),
    StudomatSubject(
        "2020./2021.Informacije i komunikacije4",
        "Informacije i komunikacije",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "4",
        "45",
        "15",
        "5,0",
        "Da",
        "obavljen (položen)",
        "2",
        "15.9.2021.",
        "2020./2021.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2020./2021.Osnove elektroenergetike4",
        "Osnove elektroenergetike",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "4",
        "45",
        "15",
        "5,0",
        "Da",
        "obavljen (položen)",
        "3",
        "8.7.2021.",
        "2020./2021.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2020./2021.Teorija sustava4",
        "Teorija sustava",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "4",
        "45",
        "15",
        "5,0",
        "Da",
        "obavljen (položen)",
        "2",
        "30.8.2021.",
        "2020./2021.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2020./2021.Vjerojatnost i statistika4",
        "Vjerojatnost i statistika",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "4",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "4",
        "9.7.2021.",
        "2020./2021.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2024./2025.Grid računalni sustavi3",
        "Grid računalni sustavi",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "3",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "5",
        "27.1.2025.",
        "2024./2025.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2024./2025.Multimedijski sustavi3",
        "Multimedijski sustavi",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "3",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "2",
        "6.2.2025.",
        "2024./2025.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2024./2025.Paralelno programiranje3",
        "Paralelno programiranje",
        "Izborni predmeti 3. sem",
        "3",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "3",
        "29.1.2025.",
        "2024./2025.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2024./2025.Poslovni informacijski sustavi3",
        "Poslovni informacijski sustavi",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "3",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "3",
        "30.1.2025.",
        "2024./2025.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2024./2025.Sigurnost bežičnih mreža3",
        "Sigurnost bežičnih mreža",
        "Izborni predmeti 3. sem",
        "3",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "5",
        "7.2.2025.",
        "2024./2025.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2024./2025.Ugradbeni računalni sustavi3",
        "Ugradbeni računalni sustavi",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "3",
        "30",
        "30",
        "5,0",
        "Da",
        "obavljen (položen)",
        "5",
        "4.2.2025.",
        "2024./2025.",
        "Računarstvo",
        true
    ),
    StudomatSubject(
        "2024./2025.Diplomski rad4",
        "Diplomski rad",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "4",
        "0",
        "15",
        "30,0",
        "Da",
        "odslušan predmet",
        "podatak nije evidentiran",
        "podatak nije evidentiran",
        "2024./2025.",
        "Računarstvo",
        false
    ),
    StudomatSubject(
        "2019./2020.Engleski jezik 11",
        "Engleski jezik 1",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "1",
        "30",
        "0",
        "3,0",
        "Da",
        "obavljen (položen)",
        "4",
        "25.2.2020.",
        "2019./2020.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2019./2020.Inženjerska grafika i prezentacija1",
        "Inženjerska grafika i prezentacija",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "1",
        "15",
        "30",
        "4,0",
        "Da",
        "obavljen (položen)",
        "4",
        "28.2.2020.",
        "2019./2020.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2019./2020.Komunikacijske vještine1",
        "Komunikacijske vještine",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "1",
        "30",
        "0",
        "3,0",
        "Da",
        "obavljen (položen)",
        "4",
        "25.2.2020.",
        "2019./2020.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2019./2020.Matematika 11",
        "Matematika 1",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "1",
        "45",
        "45",
        "7,0",
        "Da",
        "obavljen (položen)",
        "4",
        "24.2.2020.",
        "2019./2020.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2019./2020.Osnove elektrotehnike 11",
        "Osnove elektrotehnike 1",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "1",
        "45",
        "30",
        "7,0",
        "Da",
        "obavljen (položen)",
        "4",
        "26.2.2020.",
        "2019./2020.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2019./2020.Računala i programiranje1",
        "Računala i programiranje",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "1",
        "30",
        "30",
        "6,0",
        "Da",
        "obavljen (položen)",
        "4",
        "13.2.2020.",
        "2019./2020.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2019./2020.Engleski jezik 22",
        "Engleski jezik 2",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "2",
        "30",
        "0",
        "4,0",
        "Da",
        "obavljen (položen)",
        "3",
        "7.7.2020.",
        "2019./2020.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2019./2020.Fizika 12",
        "Fizika 1",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "2",
        "45",
        "45",
        "7,0",
        "Da",
        "obavljen (položen)",
        "3",
        "9.7.2020.",
        "2019./2020.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2019./2020.Matematika 22",
        "Matematika 2",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "2",
        "45",
        "45",
        "7,0",
        "Da",
        "obavljen (položen)",
        "3",
        "6.7.2020.",
        "2019./2020.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2019./2020.Osnove elektrotehnike 22",
        "Osnove elektrotehnike 2",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "2",
        "30",
        "45",
        "6,0",
        "Da",
        "obavljen (položen)",
        "3",
        "8.7.2020.",
        "2019./2020.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
    StudomatSubject(
        "2019./2020.Programiranje2",
        "Programiranje",
        "predmet se ne nalazi u grupi izbornih predmeta",
        "2",
        "30",
        "30",
        "6,0",
        "Da",
        "obavljen (položen)",
        "4",
        "9.7.2020.",
        "2019./2020.",
        "Elektrotehnika i informacijska tehnologija",
        true
    ),
)
val studomatYearInfoTestDataReal = listOf(

    StudomatYearInfo().apply {
        id = "3162546"
        courseName = "Računarstvo"
        studyProgram = "Sveučilišni diplomski studij Računarstvo"
        parallelStudy = "Drugi"
        yearOfCourse = 1
        enrollmentIndicator = "prvi upis"
        payment = false
        fundingBasis = "PU - subvencija troškova studija"
        universityCenter = "Split"
        studentRightsValidUntil = "30.9.2025."
        enrollmentDate = "19.9.2023."
        enrollmentCompleted = true
        academicYear = "2023./2024."
        href = "/studomat/hr/studiranje/upisanegodine/upis/3162546"
    },
    StudomatYearInfo().apply {
        id = "2899390"
        courseName = "Elektronika i računalno inženjerstvo"
        studyProgram =
            "Sveučilišni prijediplomski studij Elektrotehnika i informacijska tehnologija smjer Elektronika i računalno inženjerstvo"
        parallelStudy = "Ne"
        yearOfCourse = 3
        enrollmentIndicator = "prvi upis"
        payment = true
        fundingBasis = "PU - participiranje u troškovima studija"
        universityCenter = "Split"
        studentRightsValidUntil = "30.9.2022."
        enrollmentDate = "5.10.2021."
        enrollmentCompleted = true
        academicYear = "2021./2022."
        href = "/studomat/hr/studiranje/upisanegodine/upis/2899390"
    },
    StudomatYearInfo().apply {
        id = "3059773"
        courseName = "Računarstvo"
        studyProgram = "Sveučilišni prijediplomski studij Računarstvo"
        parallelStudy = "Prvi"
        yearOfCourse = 3
        enrollmentIndicator = "prvi upis"
        payment = true
        fundingBasis = "PU - puni iznos participacije"
        universityCenter = "Split"
        studentRightsValidUntil = "15.9.2023."
        enrollmentDate = "7.10.2022."
        enrollmentCompleted = true
        academicYear = "2022./2023."
        href = "/studomat/hr/studiranje/upisanegodine/upis/3059773"
    },
    StudomatYearInfo().apply {
        id = "2899270"
        courseName = "Elektrotehnika i informacijska tehnologija"
        studyProgram =
            "Sveučilišni prijediplomski studij Elektrotehnika i informacijska tehnologija smjer Elektronika i računalno inženjerstvo"
        parallelStudy = "Ne"
        yearOfCourse = 2
        enrollmentIndicator = "prvi upis"
        payment = false
        fundingBasis = "PU - subvencija troškova studija"
        universityCenter = "Split"
        studentRightsValidUntil = "30.9.2022."
        enrollmentDate = "14.10.2020."
        enrollmentCompleted = true
        academicYear = "2020./2021."
        href = "/studomat/hr/studiranje/upisanegodine/upis/2899270"
    },
    StudomatYearInfo().apply {
        id = "3334038"
        courseName = "Računarstvo"
        studyProgram = "Sveučilišni diplomski studij Računarstvo"
        parallelStudy = "Drugi"
        yearOfCourse = 2
        enrollmentIndicator = "prvi upis"
        payment = false
        fundingBasis = "PU - subvencija troškova studija"
        universityCenter = "Split"
        studentRightsValidUntil = "30.9.2025."
        enrollmentDate = "19.9.2024."
        enrollmentCompleted = true
        academicYear = "2024./2025."
        href = "/studomat/hr/studiranje/upisanegodine/upis/3334038"
    },
    StudomatYearInfo().apply {
        id = "2899125"
        courseName = "Elektrotehnika i informacijska tehnologija"
        studyProgram =
            "Sveučilišni prijediplomski studij Elektrotehnika i informacijska tehnologija smjer Elektronika i računalno inženjerstvo"
        parallelStudy = "Ne"
        yearOfCourse = 1
        enrollmentIndicator = "prvi upis"
        payment = false
        fundingBasis = "PU - subvencija troškova studija"
        universityCenter = "Split"
        studentRightsValidUntil = "30.9.2022."
        enrollmentDate = "16.7.2019."
        enrollmentCompleted = true
        academicYear = "2019./2020."
        href = "/studomat/hr/studiranje/upisanegodine/upis/2899125"
    }
)